# Generated by Django 4.2.3 on 2023-07-17 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClassMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FileClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MethodParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SourceClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SourceMethodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('return_type', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('classes', models.ManyToManyField(related_name='methods', through='storesourcecode.ClassMethod', to='storesourcecode.sourceclassmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SourceParameterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('param_type', models.CharField(max_length=200)),
                ('methods', models.ManyToManyField(related_name='parameters', through='storesourcecode.MethodParameter', to='storesourcecode.sourcemethodmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SourceFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storesourcecode.languagemodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storesourcecode.projectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SourceFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('field_type', models.CharField(max_length=200)),
                ('classes', models.ManyToManyField(related_name='fields', through='storesourcecode.ClassField', to='storesourcecode.sourceclassmodel')),
            ],
        ),
        migrations.AddField(
            model_name='sourceclassmodel',
            name='files',
            field=models.ManyToManyField(related_name='classes', through='storesourcecode.FileClass', to='storesourcecode.sourcefilemodel'),
        ),
        migrations.AddField(
            model_name='methodparameter',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storesourcecode.sourcemethodmodel'),
        ),
        migrations.AddField(
            model_name='methodparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storesourcecode.sourceparametermodel'),
        ),
        migrations.AddField(
            model_name='fileclass',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storesourcecode.sourceclassmodel'),
        ),
        migrations.AddField(
            model_name='fileclass',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storesourcecode.sourcefilemodel'),
        ),
        migrations.AddField(
            model_name='classmethod',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storesourcecode.sourceclassmodel'),
        ),
        migrations.AddField(
            model_name='classmethod',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storesourcecode.sourcemethodmodel'),
        ),
        migrations.AddField(
            model_name='classfield',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storesourcecode.sourceclassmodel'),
        ),
        migrations.AddField(
            model_name='classfield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storesourcecode.sourcefieldmodel'),
        ),
    ]
