# Generated by Django 4.2.3 on 2023-07-18 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SourceClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SourceFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('field_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SourceMethodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('return_type', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceParameterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('param_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SourceFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_source_code.languagemodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_source_code.projectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MethodParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_source_code.sourcemethodmodel')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_source_code.sourceparametermodel')),
            ],
        ),
        migrations.CreateModel(
            name='FileClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_source_code.sourceclassmodel')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_source_code.sourcefilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ClassMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_source_code.sourceclassmodel')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_source_code.sourcemethodmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ClassField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_source_code.sourceclassmodel')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_source_code.sourcefieldmodel')),
            ],
        ),
    ]
